### ISSUE TITLE
josm plugin not working

### ISSUE THREAD

**Issue by prvnpandey** [matsim-org/josm-matsim-plugin#107]
i am using josm version 15155 with matsim plugin 0.8.7-51-ga2a5dac, when i want to export shape file under matsim tab the error popup which says plugin update and after clicking on update its pop up with message plugin not found.

below is traceback messgae gererated:
{{{
URL:https://josm.openstreetmap.de/svn/trunk
Repository:UUID: 0c6e7542-c601-0410-84e7-c038aed88b3b
Last:Changed Date: 2019-06-03 00:05:30 +0200 (Mon, 03 Jun 2019)
Build-Date:2019-06-02 22:10:24
Revision:15155
Relative:URL: ^/trunk

Identification: JOSM/1.5 (15155 en) Windows 10 64-Bit
OS Build number: Windows 10 Home Single Language 1903 (18362)
Memory Usage: 789 MB / 1820 MB (507 MB allocated, but free)
Java version: 1.8.0_211-b12, Oracle Corporation, Java HotSpot(TM) 64-Bit Server VM
Screen: \Display0 1366x768
Maximum Screen Size: 1366x768
VM arguments: [-Djava.security.manager, -Djava.security.policy=file:<java.home>\lib\security\javaws.policy, -DtrustProxy=true, -Djnlpx.home=<java.home>\bin, -Djnlpx.origFilenameArg=%UserProfile%\AppData\LocalLow\Sun\Java\Deployment\cache\6.0\56\1ee8cfb8-33baea12, -Djnlpx.remove=false, -Djava.util.Arrays.useLegacyMergeSort=true, -Djnlpx.heapsize=NULL,2048m, -Djnlpx.splashport=56784, -Djnlp.application.href=https://josm.openstreetmap.de/download/josm.jnlp, -Djnlpx.jvm=<java.home>\bin\javaw.exe]
Dataset consistency test: No problems found

Plugins:
+ ejml (35049)
+ geotools (34908)
+ javafx-windows
+ jts (34908)
+ matsim (0.8.7-50-g10dd9ad)

Last errors/warnings:
- E: Failed to locate image 'new.png'
- E: Failed to locate image 'matsim-scenario.png'
- W:  null: Could not get presets icon matsim-scenario.png
- E: Failed to locate image 'images/dialogs/logo.png'
- W:  Link: Could not get presets icon images/dialogs/logo.png
- E: Handled by bug report queue: org.geotools.factory.FactoryNotFoundException: No factory of kind "CRSFactory" found.
- W: Warning - <html>JOSM could not find information about the following plugins:<ul><li>geotools</li><li>jts</li><li>javafx-windows</li><li>matsim</li><li>ejml</li></ul>The plugins are not going to be loaded.</html>
- W: java.util.zip.ZipException: error in opening zip file
- W: PluginException: : org.openstreetmap.josm.plugins.PluginException: Invalid jar file '<josm.pref>\plugins\matsim.jar.new'
- W: Failed to scan file 'matsim.jar.new' for plugin information. Skipping.

=== REPORTED CRASH DATA ===
BugReportExceptionHandler#handleException:
No data collected.

Warning issued by: BugReportExceptionHandler#handleException

**Comment by nkuehnel** [comment]
Hi,
are you sure that you tried to export to shapefile?
From the crash report it seems like you tried to export a transit schedule. At the same time the actual reason for the crash is that it seems like you have a node id that is used twice, which is not allowed:
=== STACK TRACE ===
Thread: AWT-EventQueue-2 (57) of javawsApplicationThreadGroup
**java.lang.IllegalArgumentException: There exists already a node with id = 975733283.
Existing node: [id=975733283][coord=[x=1393846.7737747796][y=4990851.158330707]][type=null][nof_inlinks=0][nof_outlinks=0]
Node to be added: [id=975733283][coord=[x=1393846.7737747373][y=4990851.15833065]][type=null][nof_inlinks=0][nof_outlinks=0].**
Node is not added to the network.
	at org.matsim.core.network.NetworkImpl.addNode(NetworkImpl.java:179)
	at org.matsim.contrib.josm.model.Export.toScenario(Export.java:43)
	at **org.matsim.contrib.josm.actions.TransitScheduleExportAction.actionPerformed(TransitScheduleExportAction.java:80)**
	at javax.swing.AbstractButton.fireActionPerformed(Unknown Source)
	at javax.swing.AbstractButton$Handler.actionPerformed(Unknown Source)
	at javax.swing.DefaultButtonModel.fireActionPerformed(Unknown Source)
	at javax.swing.DefaultButtonModel.setPressed(Unknown Source)
	at javax.swing.AbstractButton.doClick(Unknown Source)
	at javax.swing.plaf.basic.BasicMenuItemUI.doClick(Unknown Source)
	at javax.swing.plaf.basic.BasicMenuItemUI$Handler.mouseReleased(Unknown Source)
	at java.awt.Component.processMouseEvent(Unknown Source)
	at javax.swing.JComponent.processMouseEvent(Unknown Source)
	at java.awt.Component.processEvent(Unknown Source)
	at java.awt.Container.processEvent(Unknown Source)
	at java.awt.Component.dispatchEventImpl(Unknown Source)
	at java.awt.Container.dispatchEventImpl(Unknown Source)
	at java.awt.Component.dispatchEvent(Unknown Source)
	at java.awt.LightweightDispatcher.retargetMouseEvent(Unknown Source)
	at java.awt.LightweightDispatcher.processMouseEvent(Unknown Source)
	at java.awt.LightweightDispatcher.dispatchEvent(Unknown Source)
	at java.awt.Container.dispatchEventImpl(Unknown Source)
	at java.awt.Window.dispatchEventImpl(Unknown Source)
	at java.awt.Component.dispatchEvent(Unknown Source)
	at java.awt.EventQueue.dispatchEventImpl(Unknown Source)
	at java.awt.EventQueue.access$500(Unknown Source)
	at java.awt.EventQueue$3.run(Unknown Source)
	at java.awt.EventQueue$3.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.awt.EventQueue$4.run(Unknown Source)
	at java.awt.EventQueue$4.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.awt.EventQueue.dispatchEvent(Unknown Source)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
	at java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.awt.EventDispatchThread.run(Unknown Source))

**Comment by politogroup20** [comment]
I am trying to export shape file just following these below steps:
1.download the map from overpass api
2. convert into matsim layer
3. export as shape file
is this process id right if not please guide me and provide any document which help me.

**Comment by michaz** [comment]
Seems to work in current JOSM. (Can follow steps without error...)
