### ISSUE TITLE
Error in exporting shape file

### ISSUE THREAD

**Issue by magni5** [matsim-org/josm-matsim-plugin#117]
==== What steps will reproduce the problem?
1. Load data from OSM in JOSM.
2. Convert to MATSim layer.
3. Export MATSim network to shape file.

==== What is the expected result?
The MATSim network shape file is created.

==== What happens instead?
Error. Nothing is created.

==== Please provide any additional information below. Attach a screenshot if possible.

{{{
Revision:19160
Build-Date:2024-08-01 15:34:05

Identification: JOSM/1.5 (19160 it) Mac OS X 13.6.9
OS Build number: macOS 13.6.9 (22G830)
Memory Usage: 1540 MB / 4096 MB (742 MB allocated, but free)
Java version: 21.0.4+7-LTS, Azul Systems, Inc., OpenJDK 64-Bit Server VM
Look and Feel: com.apple.laf.AquaLookAndFeel
Screen: Display 69732800 1280x800x32bpp@[Unknown refresh rate] (scaling 2.00×2.00) Display 190599041 1920x1080x32bpp@60Hz (scaling 1.00×1.00)
Maximum Screen Size: 1920×1080
Best cursor sizes: 16×16→16×16, 32×32→32×32
System property file.encoding: UTF-8
System property sun.jnu.encoding: UTF-8
Locale info: it_IT
Numbers with default locale: 1234567890 -> 1234567890
VM arguments: [-Djpackage.app-version=19160, --add-modules=java.scripting,java.sql,javafx.controls,javafx.media,javafx.swing,javafx.web, --add-exports=java.base/sun.security.action=ALL-UNNAMED, --add-exports=java.desktop/com.apple.eawt=ALL-UNNAMED, --add-exports=java.desktop/com.sun.imageio.plugins.jpeg=ALL-UNNAMED, --add-exports=java.desktop/com.sun.imageio.spi=ALL-UNNAMED, --add-opens=java.base/java.lang=ALL-UNNAMED, --add-opens=java.base/java.nio=ALL-UNNAMED, --add-opens=java.base/jdk.internal.loader=ALL-UNNAMED, --add-opens=java.base/jdk.internal.ref=ALL-UNNAMED, --add-opens=java.desktop/javax.imageio.spi=ALL-UNNAMED, --add-opens=java.desktop/javax.swing.text.html=ALL-UNNAMED, --add-opens=java.prefs/java.util.prefs=ALL-UNNAMED, -Djpackage.app-path=/Applications/JOSM.app/Contents/MacOS/JOSM]
Dataset consistency test: No problems found

Plugins:
+ apache-commons (36282)
+ ejml (36176)
+ geotools (36273)
+ jackson (36273)
+ javafx (36282)
+ jaxb (36118)
+ jts (36004)
+ matsim (d70ae5a)

Last errors/warnings:
- 00026.321 E: unable to find dependency jaxb for plugin geotools
- 00026.322 E: unable to find dependency javafx for plugin matsim
- 00033.119 E: Impossibile trovare l'immagine 'open.png'
- 00033.137 E: Impossibile trovare l'immagine 'new.png'
- 00033.480 E: Impossibile trovare l'immagine 'matsim-scenario.png'
- 00033.483 W:  null: Could not get presets icon matsim-scenario.png
- 00033.485 E: Impossibile trovare l'immagine 'images/dialogs/logo.png'
- 00033.486 W:  Link: Could not get presets icon images/dialogs/logo.png
- 00367.279 E: Handled by bug report queue: java.lang.NoClassDefFoundError: org/opengis/referencing/FactoryException. Causa: java.lang.ClassNotFoundException: org.opengis.referencing.FactoryException

=== REPORTED CRASH DATA ===
BugReportExceptionHandler#handleException:
No data collected.

Warning issued by: BugReportExceptionHandler#handleException

=== STACK TRACE ===
Thread: AWT-EventQueue-0 (31) of main
java.lang.NoClassDefFoundError: org/opengis/referencing/FactoryException
	at org.matsim.contrib.josm.actions.ShapeExporter.actionPerformed(ShapeExporter.java:47)
	at java.desktop@21.0.4/javax.swing.AbstractButton.fireActionPerformed(Unknown Source)
	at java.desktop@21.0.4/javax.swing.AbstractButton$Handler.actionPerformed(Unknown Source)
	at java.desktop@21.0.4/javax.swing.DefaultButtonModel.fireActionPerformed(Unknown Source)
	at java.desktop@21.0.4/javax.swing.DefaultButtonModel.setPressed(Unknown Source)
	at java.desktop@21.0.4/javax.swing.AbstractButton.doClick(Unknown Source)
	at java.desktop@21.0.4/com.apple.laf.ScreenMenuItem.actionPerformed(Unknown Source)
	at java.desktop@21.0.4/java.awt.MenuItem.processActionEvent(Unknown Source)
	at java.desktop@21.0.4/java.awt.MenuItem.processEvent(Unknown Source)
	at java.desktop@21.0.4/java.awt.MenuComponent.dispatchEventImpl(Unknown Source)
	at java.desktop@21.0.4/java.awt.MenuComponent.dispatchEvent(Unknown Source)
	at java.desktop@21.0.4/java.awt.EventQueue.dispatchEventImpl(Unknown Source)
	at java.desktop@21.0.4/java.awt.EventQueue$4.run(Unknown Source)
	at java.desktop@21.0.4/java.awt.EventQueue$4.run(Unknown Source)
	at java.base/java.security.AccessController.doPrivileged(Unknown Source)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.desktop@21.0.4/java.awt.EventQueue$5.run(Unknown Source)
	at java.desktop@21.0.4/java.awt.EventQueue$5.run(Unknown Source)
	at java.base/java.security.AccessController.doPrivileged(Unknown Source)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.desktop@21.0.4/java.awt.EventQueue.dispatchEvent(Unknown Source)
	at java.desktop@21.0.4/java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
	at java.desktop@21.0.4/java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
	at java.desktop@21.0.4/java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
	at java.desktop@21.0.4/java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.desktop@21.0.4/java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.desktop@21.0.4/java.awt.EventDispatchThread.run(Unknown Source)
Caused by: java.lang.ClassNotFoundException: org.opengis.referencing.FactoryException
	at org.openstreetmap.josm.plugins.PluginClassLoader.loadClass(PluginClassLoader.java:82)
	at java.base/java.lang.ClassLoader.loadClass(Unknown Source)
	... 28 more
}}}

**Comment by magni5** [comment]
The same error happens using Fedora Linux 40, including
```
00026.321 E: unable to find dependency jaxb for plugin geotools
00026.322 E: unable to find dependency javafx for plugin matsim
```
