### ISSUE TITLE
NullPointer while reading osm.pbf

### ISSUE THREAD

**Issue by neuma** [matsim-org/josm-matsim-plugin#13]
Unfortunately still presistent in 0.34

osmosis altered osm.pbf dump

    completeWays=false completeRelations=false

results in NullPointer

    completeWays=true completeRelations=true

works fine

```
{{{
Revision: 7995
Repository Root: http://josm.openstreetmap.de/svn
Relative URL: ^/trunk
Last Changed Author: Don-vip
Last Changed Date: 2015-01-31 15:17:59 +0100 (Sat, 31 Jan 2015)
Build-Date: 2015-02-01 02:33:54
URL: http://josm.openstreetmap.de/svn/trunk
Repository UUID: 0c6e7542-c601-0410-84e7-c038aed88b3b
Last Changed Rev: 7995

Identification: JOSM/1.5 (7995 en) Windows 8.1 64-Bit
Memory Usage: 1481 MB / 5461 MB (849 MB allocated, but free)
Java version: 1.8.0_31, Oracle Corporation, Java HotSpot(TM) 64-Bit Server VM
Dataset consistency test: No problems found

Plugins:
- matsim (v0.3.4)
- pbf (31010)

Last errors/warnings:
- E: Failed to locate image 'matsim-scenario.png'
- W: Could not get presets icon matsim-scenario.png
- E: Failed to locate image 'images/dialogs/logo.png'
- W: Could not get presets icon images/dialogs/logo.png
- E: java.lang.NullPointerException

java.lang.NullPointerException
	at org.matsim.contrib.josm.NetworkListener$MyAggregatePrimitivesVisitor.convertWay(NetworkListener.java:402)
	at org.matsim.contrib.josm.NetworkListener$MyAggregatePrimitivesVisitor.visit(NetworkListener.java:459)
	at org.openstreetmap.josm.data.osm.Way.accept(Way.java:214)
	at org.matsim.contrib.josm.NetworkListener$MyAggregatePrimitivesVisitor.visit(NetworkListener.java:439)
	at org.matsim.contrib.josm.NetworkListener.visitAll(NetworkListener.java:68)
	at org.matsim.contrib.josm.LinksToggleDialog.notifyEverythingChanged(LinksToggleDialog.java:137)
	at org.matsim.contrib.josm.LinksToggleDialog.editLayerChanged(LinksToggleDialog.java:180)
	at org.openstreetmap.josm.gui.MapView.fireEditLayerChanged(MapView.java:188)
	at org.openstreetmap.josm.gui.MapView.setEditLayer(MapView.java:768)
	at org.openstreetmap.josm.gui.MapView.setActiveLayer(MapView.java:795)
	at org.openstreetmap.josm.gui.MapView.setActiveLayer(MapView.java:782)
	at org.openstreetmap.josm.gui.MapView.addLayer(MapView.java:347)
	at org.openstreetmap.josm.Main.addLayer(Main.java:739)
	at org.openstreetmap.josm.Main.addLayer(Main.java:721)
	at org.openstreetmap.josm.io.OsmImporter$1.run(OsmImporter.java:111)
	at java.awt.event.InvocationEvent.dispatch(Unknown Source)
	at java.awt.EventQueue.dispatchEventImpl(Unknown Source)
	at java.awt.EventQueue.access$500(Unknown Source)
	at java.awt.EventQueue$3.run(Unknown Source)
	at java.awt.EventQueue$3.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$1.doIntersectionPrivilege(Unknown Source)
	at java.awt.EventQueue.dispatchEvent(Unknown Source)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
	at java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
	at java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
	at java.awt.WaitDispatchSupport$2.run(Unknown Source)
	at java.awt.WaitDispatchSupport$4.run(Unknown Source)
	at java.awt.WaitDispatchSupport$4.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.awt.WaitDispatchSupport.enter(Unknown Source)
	at java.awt.Dialog.show(Unknown Source)
	at java.awt.Component.show(Unknown Source)
	at java.awt.Component.setVisible(Unknown Source)
	at java.awt.Window.setVisible(Unknown Source)
	at java.awt.Dialog.setVisible(Unknown Source)
	at org.openstreetmap.josm.gui.progress.PleaseWaitProgressMonitor$4.run(PleaseWaitProgressMonitor.java:172)
	at java.awt.event.InvocationEvent.dispatch(Unknown Source)
	at java.awt.EventQueue.dispatchEventImpl(Unknown Source)
	at java.awt.EventQueue.access$500(Unknown Source)
	at java.awt.EventQueue$3.run(Unknown Source)
	at java.awt.EventQueue$3.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$1.doIntersectionPrivilege(Unknown Source)
	at java.awt.EventQueue.dispatchEvent(Unknown Source)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
	at java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.awt.EventDispatchThread.run(Unknown Source)
}}}
```

**Comment by michaz** [comment]
@nkuehnel that was most probably me. I remember deleting something about "isCompleted" or so because I didn't get it. Let's write a test for that: Save a .osm.xml file which doesn't contain anything but an incomplete way, and write a test which loads it and converts it.

**Comment by michaz** [comment]
Oh cool, you already fixed it. Let's write that test anyway.
