### ISSUE TITLE
NullPointerException while converting transit data from OSM server

### ISSUE THREAD

**Issue by briemla** [matsim-org/josm-matsim-plugin#19]
Converting a part of OSM server maps with transit data results in a NullPointerException.

Steps to reproduce:

1. Activate transit support in converter options
2. Load data from OSM server with some transit data
3. Convert layer to matsim

The following exception will be thrown:
```
java.lang.NullPointerException
	at java.util.concurrent.ConcurrentHashMap.get(ConcurrentHashMap.java:936)
	at org.matsim.api.core.v01.Id.create(Id.java:64)
	at org.matsim.contrib.josm.NetworkListener$ConvertVisitor.createTransitRoute(NetworkListener.java:604)
	at org.matsim.contrib.josm.NetworkListener$ConvertVisitor.visit(NetworkListener.java:515)
	at org.matsim.contrib.josm.NetworkListener.visitAll(NetworkListener.java:81)
	at org.matsim.contrib.josm.LayerConverter.run(LayerConverter.java:42)
	at org.matsim.contrib.josm.ConvertTask.realRun(ConvertTask.java:48)
	at org.openstreetmap.josm.gui.PleaseWaitRunnable.doRealRun(PleaseWaitRunnable.java:93)
	at org.openstreetmap.josm.gui.PleaseWaitRunnable.access$000(PleaseWaitRunnable.java:25)
	at org.openstreetmap.josm.gui.PleaseWaitRunnable$4.run(PleaseWaitRunnable.java:157)
	at java.lang.Thread.run(Thread.java:745)
```

I tried it with different areas around Karlsruhe in Germany. The above exception was thrown in any case. The exception will not be thrown if there is no transit data in the area to be converted.

Because github does not support adding files other than images, I did not add an example map. If it is needed, I will rename the file to an image type and upload it.

**Comment by michaz** [comment]
Thanks! Be advised, however, that the transit feature is not very useful yet when working with OSM data (it works for editing imported, native MATSim networks though).
Could you maybe let us know your requirements? Perhaps we can improve this step by step.
Most important: Do you require PT and cars sharing the same infrastructure (i.e. buses drive on the road network) or would you be fine with "virtual" links for busses, where they flow independently of cars?

**Comment by briemla** [comment]
We try to build up a model of Karlsruhe using as much open data as possible. Ideally we would like to automatically use the maps and transit lines available via OSM to build up our network. The departure times and so on are not available on OSM so, we will add them manually.
The sharing feature would be quite useful for us, because we want to model the rush hour in the morning and afternoon, where buses get stuck in traffic jams produced by other agents. 
But in the first try I think it would be ok to use "virtual" links. I will contact my professor to ask how "real" the results of the simulation should be, because at the moment this is just a student project to evaluate matsim and open data for traffic simulation.
