### ISSUE TITLE
IllegalArgumentException: Listener Links/Nodes was already registered

### ISSUE THREAD

**Issue by don-vip** [matsim-org/josm-matsim-plugin#49]
Seen in [JOSM plugin integration test](https://josm.openstreetmap.de/jenkins/job/JOSM/lastCompletedBuild/jdk=JDK8/testReport/org.openstreetmap.josm.plugins/PluginHandlerTestIT/testValidityOfAvailablePlugins/):

    Caused by: org.openstreetmap.josm.plugins.PluginException: An error occurred in plugin matsim
	... 20 more
    Caused by: java.lang.reflect.InvocationTargetException
    	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    	at java.lang.reflect.Method.invoke(Method.java:498)
    	at org.openstreetmap.josm.plugins.PluginProxy.mapFrameInitialized(PluginProxy.java:45)
	... 18 more
    Caused by: java.lang.IllegalArgumentException: Listener Links/Nodes (instance of org.matsim.contrib.josm.gui.LinksToggleDialog) was already registered.
    	at org.openstreetmap.josm.tools.ListenerList.failAdd(ListenerList.java:108)
    	at org.openstreetmap.josm.tools.ListenerList.ensureNotInList(ListenerList.java:102)
    	at org.openstreetmap.josm.tools.ListenerList.addListener(ListenerList.java:95)
    	at org.openstreetmap.josm.data.Preferences.addPreferenceChangeListener(Preferences.java:231)
    	at org.matsim.contrib.josm.gui.LinksToggleDialog.<init>(LinksToggleDialog.java:77)
    	at org.matsim.contrib.josm.MATSimPlugin.mapFrameInitialized(MATSimPlugin.java:140)
	... 23 more

**Comment by michaz** [comment]
Fixed, cheers.
