### ISSUE TITLE
Cannot Convert to MATSim layer

### ISSUE THREAD

**Issue by kowinter** [matsim-org/josm-matsim-plugin#75]
When converting to a MATSim Layer, an error occurs (the same as reported here: https://matsim.atlassian.net/wiki/spaces/MATPUB/pages/18317321/JOSM-Plugin?focusedCommentId=132218887#comment-132218887). Updating the plugin to v0.8.3-3 did not resolve the issue. 

Below the crash report:
{{{
URL:http://josm.openstreetmap.de/svn/trunk
Repository:UUID: 0c6e7542-c601-0410-84e7-c038aed88b3b
Last:Changed Date: 2017-11-26 14:31:59 +0100 (Sun, 26 Nov 2017)
Build-Date:2017-11-26 13:34:54
Revision:13170
Relative:URL: ^/trunk

Identification: JOSM/1.5 (13170 en) Windows 7 64-Bit
OS Build number: Windows 7 Enterprise (7601)
Memory Usage: 8087 MB / 8087 MB (7263 MB allocated, but free)
Java version: 1.8.0_144-b01, Oracle Corporation, Java HotSpot(TM) 64-Bit Server VM
Screen: \Display0 1920x1080, \Display1 1920x1080
Maximum Screen Size: 1920x1080
Dataset consistency test: No problems found

Plugins:
+ apache-commons (33668)
+ apache-http (32699)
+ jts (32699)
+ matsim (v0.8.3-3-gfaca0ec)
+ pbf (33568)

Map paint styles:
+ https://josm.openstreetmap.de/josmfile?page=Styles/PublicTransport&zip=1
- https://josm.openstreetmap.de/josmfile?page=Styles/PublicTransportV2&zip=1

Last errors/warnings:
- W: No configuration settings found.  Using hardcoded default values for all pools.
- E: Failed to locate image 'matsim-scenario.png'
- W:  null: Could not get presets icon matsim-scenario.png
- E: Failed to locate image 'images/dialogs/logo.png'
- W:  Link: Could not get presets icon images/dialogs/logo.png
- E: Handled by bug report queue: java.lang.RuntimeException

=== REPORTED CRASH DATA ===
BugReportExceptionHandler#handleException:
No data collected.

Warning issued by: BugReportExceptionHandler#handleException

=== STACK TRACE ===
Thread: org.matsim.contrib.josm.actions.ConvertAction$1 (154)
java.lang.RuntimeException
	at org.matsim.contrib.josm.model.Export.lambda$createFacilities$6(Export.java:162)
	at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(Unknown Source)
	at java.util.stream.ReferencePipeline$3$1.accept(Unknown Source)
	at java.util.Iterator.forEachRemaining(Unknown Source)
	at java.util.Spliterators$IteratorSpliterator.forEachRemaining(Unknown Source)
	at java.util.stream.AbstractPipeline.copyInto(Unknown Source)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(Unknown Source)
	at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(Unknown Source)
	at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(Unknown Source)
	at java.util.stream.AbstractPipeline.evaluate(Unknown Source)
	at java.util.stream.ReferencePipeline.forEach(Unknown Source)
	at org.matsim.contrib.josm.model.Export.createFacilities(Export.java:136)
	at org.matsim.contrib.josm.model.Export.toScenario(Export.java:56)
	at org.matsim.contrib.josm.model.LayerConverter.convertWithFullTransit(LayerConverter.java:30)
	at org.matsim.contrib.josm.actions.ConvertAction$1.realRun(ConvertAction.java:60)
	at org.openstreetmap.josm.gui.PleaseWaitRunnable.doRealRun(PleaseWaitRunnable.java:95)
	at java.lang.Thread.run(Unknown Source)
}}}

**Comment by nkuehnel** [comment]
hey,
I think the plugin repository site needed some time to update to the new release. Could you please try again to update the plugin? As for the moment it will have a weird version number and should look like this:
![image](https://user-images.githubusercontent.com/9531582/33930430-2dc502f4-dfed-11e7-8b6b-511cdc57d3fb.png)

It should work once you use this version. Sorry for the inconvenience

**Comment by kowinter** [comment]
Thank you for your help, it works now.

**Comment by nkuehnel** [comment]
Great!
