### ISSUE TITLE
Cannot convert network into Shapefile

### ISSUE THREAD

**Issue by afarner** [matsim-org/josm-matsim-plugin#93]
Working at ETH for a project and trying to get zurich_network into a shapefile. Unfortunately the following error occurs. Also tried with more simple networks, still error.
----------------------------------------
{{{
URL:https://josm.openstreetmap.de/svn/trunk
Repository:UUID: 0c6e7542-c601-0410-84e7-c038aed88b3b
Last:Changed Date: 2018-05-31 00:51:20 +0200 (Thu, 31 May 2018)
Build-Date:2018-05-30 22:58:01
Revision:13878
Relative:URL: ^/trunk

Identification: JOSM/1.5 (13878 en) Windows 10 64-Bit
OS Build number: Windows 10 Enterprise 1703 (15063)
Memory Usage: 932 MB / 932 MB (309 MB allocated, but free)
Java version: 1.8.0_152-b16, Oracle Corporation, Java HotSpot(TM) 64-Bit Server VM
Screen: \Display0 1920x1080
Maximum Screen Size: 1920x1080
Dataset consistency test: No problems found

Plugins:
+ apache-commons (34109)
+ apache-http (34109)
+ ejml (34126)
+ geotools (34125)
+ jts (34038)
+ matsim (v0.9.2)
+ opendata (34196)
+ utilsplugin2 (34263)

Tagging presets:
+ B:\IVT\JOSM\Presets\walkway.xml

Last errors/warnings:
- W: No configuration settings found.  Using hardcoded default values for all pools.
- E: Failed to locate image 'new.png'
- E: Failed to locate image 'matsim-scenario.png'
- W:  null: Could not get presets icon matsim-scenario.png
- E: Failed to locate image 'images/dialogs/logo.png'
- W:  Link: Could not get presets icon images/dialogs/logo.png
- E: Handled by bug report queue: org.geotools.factory.FactoryNotFoundException: No factory of kind "CRSFactory" found.
- E: Handled by bug report queue: org.geotools.factory.FactoryNotFoundException: No factory of kind "CRSFactory" found.
- W: Warning - <html>JOSM could not find information about the following plugins:<ul><li>utilsplugin2</li><li>apache-commons</li><li>geotools</li><li>opendata</li><li>jts</li><li>matsim</li><li>ejml</li><li>apache-http</li></ul>The plugins are not going to be loaded.</html>

=== REPORTED CRASH DATA ===
BugReportExceptionHandler#handleException:
No data collected.

Warning issued by: BugReportExceptionHandler#handleException

=== STACK TRACE ===
Thread: AWT-EventQueue-0 (20) of main
org.geotools.factory.FactoryNotFoundException: No factory of kind "CRSFactory" found.
	at org.geotools.factory.FactoryRegistry.getServiceProvider(FactoryRegistry.java:375)
	at org.geotools.factory.FactoryCreator.getServiceProvider(FactoryCreator.java:145)
	at org.geotools.referencing.ReferencingFactoryFinder.getFactory(ReferencingFactoryFinder.java:197)
	at org.geotools.referencing.ReferencingFactoryFinder.getCRSFactory(ReferencingFactoryFinder.java:288)
	at org.geotools.referencing.CRS.parseWKT(CRS.java:535)
	at org.matsim.core.utils.geometry.geotools.MGC.getCRS(MGC.java:172)
	at org.matsim.contrib.josm.actions.ShapeExporter.actionPerformed(ShapeExporter.java:47)
	at javax.swing.AbstractButton.fireActionPerformed(Unknown Source)
	at javax.swing.AbstractButton$Handler.actionPerformed(Unknown Source)
	at javax.swing.DefaultButtonModel.fireActionPerformed(Unknown Source)
	at javax.swing.DefaultButtonModel.setPressed(Unknown Source)
	at javax.swing.AbstractButton.doClick(Unknown Source)
	at javax.swing.plaf.basic.BasicMenuItemUI.doClick(Unknown Source)
	at javax.swing.plaf.basic.BasicMenuItemUI$Handler.mouseReleased(Unknown Source)
	at java.awt.Component.processMouseEvent(Unknown Source)
	at javax.swing.JComponent.processMouseEvent(Unknown Source)
	at java.awt.Component.processEvent(Unknown Source)
	at java.awt.Container.processEvent(Unknown Source)
	at java.awt.Component.dispatchEventImpl(Unknown Source)
	at java.awt.Container.dispatchEventImpl(Unknown Source)
	at java.awt.Component.dispatchEvent(Unknown Source)
	at java.awt.LightweightDispatcher.retargetMouseEvent(Unknown Source)
	at java.awt.LightweightDispatcher.processMouseEvent(Unknown Source)
	at java.awt.LightweightDispatcher.dispatchEvent(Unknown Source)
	at java.awt.Container.dispatchEventImpl(Unknown Source)
	at java.awt.Window.dispatchEventImpl(Unknown Source)
	at java.awt.Component.dispatchEvent(Unknown Source)
	at java.awt.EventQueue.dispatchEventImpl(Unknown Source)
	at java.awt.EventQueue.access$500(Unknown Source)
	at java.awt.EventQueue$3.run(Unknown Source)
	at java.awt.EventQueue$3.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.awt.EventQueue$4.run(Unknown Source)
	at java.awt.EventQueue$4.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.awt.EventQueue.dispatchEvent(Unknown Source)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
	at java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.awt.EventDispatchThread.run(Unknown Source)
}}}

**Comment by nkuehnel** [comment]
thanks for reporting, seems to be a dependency error, I will look into that

**Comment by afarner** [comment]
Thank you for the fast fix!
With JOSM Latest Nightly and Plugin update to 0.9.4 it works again now.

**Comment by nkuehnel** [comment]
Great!
